server:
  port: 8080

spring:
  application:
    name: mail-api
  datasource:
    url: jdbc:postgresql://localhost:5432/da-platform-db
    username:
    password:
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: email-service-group
      properties:
        spring.json.trusted.packages: "com.example.mailapi.controller.request"
        value-type: com.example.mailapi.controller.request.EmailRequest