server:
  port: 8080

spring:
  application:
    name: mail-api
  datasource:
    url: jdbc:postgresql://localhost:5432/da-platform-db
    username:
    password:
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update